version: "3.2"

services:
  dynamodb-developer-hub-api:
    image: dynamodb-developer-hub-api
    build:
      context: DeveloperHubAPI/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
     - DynamoDb_LocalMode=true
     - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  dynamodb-developer-hub-api-test:
    image: dynamodb-developer-hub-api-test
    build:
      context: .
      dockerfile: DeveloperHubAPI.Tests/Dockerfile
    environment:
     - DynamoDb_LocalMode=true
     - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local
    links:
     - dynamodb-database

 dynamodb-database:
    image: amazon/dynamodb-local
    ports:
     - 8000:8000
